repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    hooks:
      - id: mypy
        additional_dependencies: [
          mypy-boto3-dynamodb==1.34.0,
          mypy-boto3-secretsmanager==1.34.0,
        ]
        args: ["--config-file", "mypy.ini"]
