AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sleep Quality Advisor - Backend

Parameters:
  IngestSharedSecretName:
    Type: String
    Default: ingest/shared/secret
    Description: Secrets Manager secret name for the shared secret used by the authorizer
  FitbitRefreshSecretName:
    Type: String
    Default: fitbit/refresh/token
  FitbitClientSecretName:
    Type: String
    Default: fitbit/client/secret
  FitbitClientIdParamName:
    Type: String
    Default: /fitbit/client/id
  FitbitCodeVerifierSecretName:
    Type: String
    Default: fitbit/code/verifier
  ScheduleExpression:
    Type: String
    Default: cron(10 7 * * ? *) # 07:10 UTC daily
  ReportEmailAddress:
    Type: String
    Default: "changeme@example.com"
    Description: Email address for weekly sleep health reports (must be verified in SES)
  AgentRuntimeArn:
    Type: String
    Default: ""
    Description: ARN of the Health Analyzer Agent deployed to AgentCore Runtime (populated after agent deployment)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Tracing: Active
    Architectures:
      - arm64
    Environment:
      Variables:
        ENV_READINGS_TABLE: !Ref EnvReadingsTable
        SLEEP_SESSIONS_TABLE: !Ref SleepSessionsTable
        INGEST_SHARED_SECRET_NAME: !Ref IngestSharedSecretName
    Layers: []

Resources:
  # DynamoDB tables
  EnvReadingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: day
          AttributeType: S
        - AttributeName: ts_min
          AttributeType: N
      KeySchema:
        - AttributeName: day
          KeyType: HASH
        - AttributeName: ts_min
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  SleepSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sleepDate
          AttributeType: S
        - AttributeName: segmentStart
          AttributeType: S
      KeySchema:
        - AttributeName: sleepDate
          KeyType: HASH
        - AttributeName: segmentStart
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true

  # Ingest shared secret (used by API authorizer)
  IngestSharedSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref IngestSharedSecretName
      Description: Shared secret for ingest authorizer
      GenerateSecretString:
        PasswordLength: 32
        ExcludePunctuation: true
        ExcludeUppercase: true
      

  # Bootstrap: Fitbit related secrets and parameters with default values
  FitbitRefreshSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref FitbitRefreshSecretName
      Description: Refresh token for Fitbit OAuth flow
      SecretString: "<empty>"

  FitbitClientSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref FitbitClientSecretName
      Description: Fitbit API client secret
      SecretString: "<empty>"

  FitbitCodeVerifierSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref FitbitCodeVerifierSecretName
      Description: Temporary PKCE code_verifier storage for Fitbit authorization
      SecretString: "<empty>"

  FitbitClientIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref FitbitClientIdParamName
      Type: String
      Value: "<empty>"

  # SQS Queues
  EnvIngestDLQ:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days

  EnvIngestQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt EnvIngestDLQ.Arn
        maxReceiveCount: 5

  # Lambda: SQS Consumer -> DynamoDB writer
  EnvIngestConsumer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: env_ingest_consumer/handler.lambda_handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt EnvReadingsTable.Arn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt EnvIngestQueue.Arn
            BatchSize: 10
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures

  # Lambda: Authorizer for API Gateway to validate shared secret header
  EnvIngestAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: env_ingest_authorizer/handler.lambda_handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref IngestSharedSecret

  # Fitbit callback Lambda
  FitbitCallback:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: fitbit_callback/handler.lambda_handler
      Environment:
        Variables:
          FITBIT_REFRESH_SECRET_NAME: !Ref FitbitRefreshSecretName
          FITBIT_CLIENT_SECRET_NAME: !Ref FitbitClientSecretName
          FITBIT_CLIENT_ID_PARAM_NAME: !Ref FitbitClientIdParamName
          FITBIT_CODE_VERIFIER_SECRET_NAME: !Ref FitbitCodeVerifierSecretName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:PutSecretValue
              Resource: !Ref FitbitRefreshSecret
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: '*'
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
      Events:
        HttpCallback:
          Type: Api
          Properties:
            Path: /fitbit/callback
            Method: GET
            

  # Fitbit authorize Lambda (redirects to Fitbit OAuth with PKCE)
  FitbitAuthorize:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: fitbit_authorize/handler.lambda_handler
      Environment:
        Variables:
          FITBIT_CLIENT_ID_PARAM_NAME: !Ref FitbitClientIdParamName
          FITBIT_CODE_VERIFIER_SECRET_NAME: !Ref FitbitCodeVerifierSecretName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:PutSecretValue
              Resource: !Ref FitbitCodeVerifierSecret
      Events:
        HttpAuthorize:
          Type: Api
          Properties:
            Path: /fitbit/authorize
            Method: GET
            

  
      

  # Fitbit fetch Lambda (scheduled)
  FitbitFetch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: fitbit_fetch/handler.lambda_handler
      Timeout: 60
      Environment:
        Variables:
          FITBIT_REFRESH_SECRET_NAME: !Ref FitbitRefreshSecretName
          FITBIT_CLIENT_SECRET_NAME: !Ref FitbitClientSecretName
          FITBIT_CLIENT_ID_PARAM_NAME: !Ref FitbitClientIdParamName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: '*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt SleepSessionsTable.Arn
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:PutSecretValue
              Resource: !Ref FitbitRefreshSecret
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Enabled: true


  # API Gateway (REST) -> SQS with Lambda TOKEN authorizer via SAM Api Auth
  IngestApiV2:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Auth:
        DefaultAuthorizer: IngestTokenAuth
        Authorizers:
          IngestTokenAuth:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt EnvIngestAuthorizer.Arn
      DefinitionBody:
        swagger: "2.0"
        info:
          title: Ingest API
          version: "1.0"
        basePath: "/prod"
        schemes:
          - https
        paths:
          /ingest:
            post:
              security:
                - IngestTokenAuth: []
              responses:
                "200":
                  description: OK
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                credentials: !GetAtt ApiGatewaySqsRole.Arn
                uri: !Sub arn:aws:apigateway:${AWS::Region}:sqs:path/${AWS::AccountId}/${EnvIngestQueue.QueueName}
                passthroughBehavior: NEVER
                requestParameters:
                  integration.request.header.Content-Type: "'application/x-www-form-urlencoded'"
                requestTemplates:
                  application/json: |
                    Action=SendMessage&MessageBody=$util.urlEncode($util.escapeJavaScript($input.body))
                responses:
                  default:
                    statusCode: "200"

  ApiGatewaySqsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ApiGwSqsSend
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt EnvIngestQueue.Arn

  # ========================================================================
  # Weekly Health Report System
  # ========================================================================

  # SSM Parameter for report email
  ReportEmailParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /sleep-advisor/report-email
      Type: String
      Value: !Ref ReportEmailAddress
      Description: Email address for weekly sleep health reports

  # MCP Server Lambda - Provides DynamoDB data access via MCP protocol
  MCPServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: mcp_server/handler.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 512
      Architectures:
        - arm64
      Environment:
        Variables:
          ENV_READINGS_TABLE: !Ref EnvReadingsTable
          SLEEP_SESSIONS_TABLE: !Ref SleepSessionsTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:GetItem
              Resource:
                - !GetAtt EnvReadingsTable.Arn
                - !GetAtt SleepSessionsTable.Arn

  # Function URL for MCP Server (allows AgentCore agent to invoke)
  MCPServerFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !GetAtt MCPServerFunction.Arn
      AuthType: AWS_IAM
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - POST
          - GET
        AllowHeaders:
          - "*"

  # Permission for Function URL
  MCPServerFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MCPServerFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: AWS_IAM

  # Weekly Report Orchestrator Lambda
  WeeklyReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: weekly_report/handler.lambda_handler
      Runtime: python3.12
      Timeout: 300
      MemorySize: 1024
      Architectures:
        - arm64
      Environment:
        Variables:
          AGENT_ARN: !Ref AgentRuntimeArn
          EMAIL_PARAMETER_NAME: /sleep-advisor/report-email
          SENDER_EMAIL: !Ref ReportEmailAddress
          AWS_REGION: !Ref AWS::Region
      Policies:
        - Version: '2012-10-17'
          Statement:
            # Permission to invoke AgentCore Runtime
            - Effect: Allow
              Action:
                - bedrock-agentcore:InvokeAgentRuntime
              Resource: !Ref AgentRuntimeArn
              Condition:
                StringEquals:
                  "aws:RequestedRegion": !Ref AWS::Region
            # Permission to read email from SSM
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/sleep-advisor/report-email"
            # Permission to send email via SES
            - Effect: Allow
              Action:
                - ses:SendRawEmail
                - ses:SendEmail
              Resource: "*"
      Events:
        WeeklySchedule:
          Type: Schedule
          Properties:
            Schedule: "cron(0 8 ? * MON *)"  # Every Monday at 8:00 AM UTC
            Description: Trigger weekly sleep health report generation
            Enabled: true

Outputs:
  ApiUrl:
    Description: Base URL for the API stage
    Value: !Sub https://${IngestApiV2}.execute-api.${AWS::Region}.amazonaws.com/prod
  FitbitCallbackUrl:
    Description: URL for the Fitbit callback
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fitbit/callback
  FitbitAuthorizeUrl:
    Description: URL for the Fitbit authorize redirect
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fitbit/authorize

  EnvReadingsTableName:
    Description: Physical name of EnvReadingsTable
    Value: !Ref EnvReadingsTable
    Export:
      Name: !Sub "${AWS::StackName}-EnvReadingsTable"

  SleepSessionsTableName:
    Description: Physical name of SleepSessionsTable
    Value: !Ref SleepSessionsTable
    Export:
      Name: !Sub "${AWS::StackName}-SleepSessionsTable"

  MCPServerFunctionUrl:
    Description: MCP Server Function URL (used by AgentCore agent)
    Value: !GetAtt MCPServerFunctionUrl.FunctionUrl

  MCPServerFunctionArn:
    Description: MCP Server Function ARN
    Value: !GetAtt MCPServerFunction.Arn

  WeeklyReportFunctionArn:
    Description: Weekly Report Orchestrator Function ARN
    Value: !GetAtt WeeklyReportFunction.Arn

  ReportEmailParameter:
    Description: SSM Parameter name for report email
    Value: /sleep-advisor/report-email

